// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhp1FLHkdjwX6tc_I4DbJg-Kok8k12A1s',
    appId: '1:709951697598:web:40748ccc195f18e353a4ef',
    messagingSenderId: '709951697598',
    projectId: 'simpletaxautoextraction',
    authDomain: 'simpletaxautoextraction.firebaseapp.com',
    storageBucket: 'simpletaxautoextraction.firebasestorage.app',
    measurementId: 'G-24K5STQY14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDzJD1R0YU0P_njQiieneEjRe3Ac2W8Ek',
    appId: '1:709951697598:android:a0c3e27652ba32ce53a4ef',
    messagingSenderId: '709951697598',
    projectId: 'simpletaxautoextraction',
    storageBucket: 'simpletaxautoextraction.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF5oKat_PXK3RtIeLlFPCDnqwfpZi1uEg',
    appId: '1:709951697598:ios:147286011778896f53a4ef',
    messagingSenderId: '709951697598',
    projectId: 'simpletaxautoextraction',
    storageBucket: 'simpletaxautoextraction.firebasestorage.app',
    iosBundleId: 'com.example.simpletaxautoextraction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF5oKat_PXK3RtIeLlFPCDnqwfpZi1uEg',
    appId: '1:709951697598:ios:147286011778896f53a4ef',
    messagingSenderId: '709951697598',
    projectId: 'simpletaxautoextraction',
    storageBucket: 'simpletaxautoextraction.firebasestorage.app',
    iosBundleId: 'com.example.simpletaxautoextraction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhp1FLHkdjwX6tc_I4DbJg-Kok8k12A1s',
    appId: '1:709951697598:web:4bd28c304486192153a4ef',
    messagingSenderId: '709951697598',
    projectId: 'simpletaxautoextraction',
    authDomain: 'simpletaxautoextraction.firebaseapp.com',
    storageBucket: 'simpletaxautoextraction.firebasestorage.app',
    measurementId: 'G-EPG4KFDBZX',
  );
}
